name: Test Flaky

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.452219EE23B2DF5DCBB800EE9842FCB5CB1CFA49 }}  
          passphrase: ${{ secrets.secret }}
      - name: sign in
        run: gpg --default-key 452219EE23B2DF5DCBB800EE9842FCB5CB1CFA49 --sign pom.xml
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Maven
        run: mvn clean install -Drat.skip -Dskiptests -Dcheckstyle.skip -Dmaven.test.skip=true
      - name: Compile the project
        run: mvn test-compile -pl wro4j-extensions -am -Drat.skip -Dskiptests -Dcheckstyle.skip
  
      # - name: Run tests
      #   run: mvn -pl wro4j-extensions test -Dtest=ro.isdc.wro.extensions.processor.support.sass.TestRubySassEngine#shouldProcessValidCss
        
      # - name: Set up JDK 8 for NonDex
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'adopt'
      #     java-version: '8'
  
      - name: Run NonDex to check for flaky tests
        run: mvn -pl wro4j-extensions edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=ro.isdc.wro.extensions.processor.support.sass.TestRubySassEngine#shouldProcessValidCss -DnondexRuns=20
